### ISSUE TITLE
Cannot compile on Ubuntu 22.04

### ISSUE THREAD

**Issue by hellocatfood** [johanberntsson/simple-arpeggiator-lv2#4]
I'm trying to compile the plugi non Ubuntu 22.04. It fails at the `make ` stage:
```
g++ simplearpeggiator_gui_qt5.cpp -o simplearpeggiator_gui_qt5.so -shared -fPIC -Wl,--no-undefined `pkg-config --cflags --libs Qt5Core Qt5Gui Qt5Widgets`
simplearpeggiator_gui_qt5.cpp:400:35: error: invalid conversion from ‘void* (*)(const _LV2UI_Descriptor*, const char*, const char*, LV2UI_Write_Function, LV2UI_Controller, void**, const LV2_Feature* const*)’ {aka ‘void* (*)(const _LV2UI_Descriptor*, const char*, const char*, void (*)(void*, unsigned int, unsigned int, unsigned int, const void*), void*, void**, const LV2_Feature* const*)’} to ‘void* (*)(const LV2UI_Descriptor*, const char*, const char*, LV2UI_Write_Function, LV2UI_Controller, void**, const LV2_Feature* const*)’ {aka ‘void* (*)(const LV2UI_Descriptor*, const char*, const char*, void (*)(void*, unsigned int, unsigned int, unsigned int, const void*), void*, void**, const LV2_Feature* const*)’} [-fpermissive]
  400 |     SIMPLEARPEGGIATOR_URI "#qt5", instantiate, cleanup, port_event, extension_data
      |                                   ^~~~~~~~~~~
      |                                   |
      |                                   void* (*)(const _LV2UI_Descriptor*, const char*, const char*, LV2UI_Write_Function, LV2UI_Controller, void**, const LV2_Feature* const*) {aka void* (*)(const _LV2UI_Descriptor*, const char*, const char*, void (*)(void*, unsigned int, unsigned int, unsigned int, const void*), void*, void**, const LV2_Feature* const*)}
make: *** [Makefile:36: simplearpeggiator_gui_qt5.so] Error 1
```
